### ISSUE TITLE
Feature Request: better AI support with entities for each type of object (request for help/guidance)

### ISSUE THREAD

**Issue by cpainchaud** [fwestenberg/reolink_dev#281]
This is especially targeted at @fwestenberg 

Currently there is only Motion Detection flag along with some attributes for the various objects detections which require additional/complicated manual steps to get them as entities in HASS.

I think they deserve their own entity for each type of object (person, vehicle, (and soon pet)) . Yet I am having issues with the delay period you have attached to motion detection which will condition refresh of AI states and may make it miss some events.

I have created a new class for object type detection:
https://github.com/cpainchaud/reolink_dev/commit/c0144fbbed24ee3ed35f922cc855a7833a3fd2d6

```
async def async_setup_entry(hass, config_entry, async_add_devices):
    """Set up the Reolink IP Camera switches."""
    sensor = MotionSensor(hass, config_entry)
    person_detected_sensor = ObjectDetectedSensor(hass, config_entry, 'person')
    vehicle_detected_sensor = ObjectDetectedSensor(hass, config_entry, 'vehicle')

    async_add_devices([sensor, person_detected_sensor, vehicle_detected_sensor], update_before_add=False)
```

but it would also be nice to add them only if the camera supports them

**Comment by yagrasdemonde** [comment]
Very good idea, I’m agree

**Comment by fwestenberg** [comment]
@cpainchaud I really appreciate all the excellent work you've done so far and added you as a contributor to this project. 
I do not have any additional needs, but feel free to implement them if you like. Personally I cannot find all time I need to spend on this project right now (I do the best I can!). 
But we should probably be aware not to create too many switches and sensors (because there is so many functionality in the camera!).

**Comment by cpainchaud** [comment]
implemented
