### ISSUE TITLE
Can't load rtmp stream HA 2021.10.1, integration v0.26

### ISSUE THREAD

**Issue by drjjr2** [fwestenberg/reolink_dev#301]
**Describe the bug**
Errors in log 
` ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtmp://10.0.0.40:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=<mypassword>`

**To Reproduce**
Add camera, can't view stream. Motion detectors seem to be working and an idle image will show, but it won't stream

**Expected behavior**
Able to view stream.

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version HA 2021.10.1
 - Reolink camera model RLC-810A via RLN16-410
 - Camera firmware number 3.0.0.494_21073003
 - Running v0.26 of integration

**Additional context**
I feel like this was working prior to updating to 2021.10.0 (and now 2021.10.1)

**Comment by cpainchaud** [comment]
Hi, please first update to latest version as I see at least one error which was already fixed.

Can you then try RSTP protocol rather than RTMP? also please try to open the RTSP stream rtmp://10.0.0.40:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=<mypassword> with a desktop client to see if it's actually wortking

**Comment by cpainchaud** [comment]
Reolink's software is so bad .... who knows what they're up to ... each firmware fixes some issues but creates new ones....
