### ISSUE TITLE
Rotate Image stream from camera in 90º

### ISSUE THREAD

**Issue by MiAutomations** [fwestenberg/reolink_dev#309]
Hello 

I just need to rotate the video stream from onde camera in 90º 

I found this ... 

camera:
    - platform: onvif
      host: 192.168.1.189
      name: IP cam
      port: 8000
      username: admin
      password: 123456
      extra_arguments: -vf "transpose=1"

But I'm not able to use this in the reolink cameras .... 

Is there any way to perform this? Or can you please add this as a new feature for this integration ? 

Thank you and best regards

**Comment by xannor** [comment]
Is there a reason you want to rotate the stream in software, instead of having the camera do it? I don't know about all the cameras, but most of the ones I have worked with have an option in their web interface that lets you rotate. Usually Flip/Rotation (for top to bottom rotation) and Mirror for (left to right rotation.)

You should be able to use a combination of these two to orient the camera correctly.

**Comment by MiAutomations** [comment]
The Reolink cameras can't rotate the image/stream 90º in the reolink software or webconfig page .

And I can't rotate the camera physical in this particular case  the last option is to rotate the stream over the ONVIF integration if possible ....

Thank you
