### ISSUE TITLE
Add availability sensor

### ISSUE THREAD

**Issue by scstraus** [fwestenberg/reolink_dev#53]
Pursuant to [this issue](https://github.com/fwestenberg/reolink/issues/28), it would be very useful to have a sensor which told us when the component is not actually able to connect to the camera and is therefore not actually updating. This would help me to show the camera in the UI only when there's actually something to show.

**Comment by IvanPenyaHuguet** [comment]
Maybe we can add this, that will be helpful for knowing if the cam has lose connection because other things like turn off and trigger automations. 
What will be the best way of checking this? A new state checking if the token is None? I don't know if the token resets everytime it loses connection but I think it should now.

**Comment by scstraus** [comment]
I also don’t know about the token. But it appears to give an error when it’s not able to give the stream, so I think that would do it.

**Comment by fwestenberg** [comment]
Added in v0.8.
